//-
// Copyright (c) 2015,2021 University of Cambridge
// All rights reserved.
//
// This software was developed by Stanford University and the University of Cambridge Computer Laboratory 
// under National Science Foundation under Grant No. CNS-0855268,
// the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
// by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"), 
// as part of the DARPA MRC research programme,
// and by the University of Cambridge Computer Laboratory under EPSRC EARL Project
// EP/P025374/1 alongside support from Xilinx Inc.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
// license agreements.  See the NOTICE file distributed with this work for
// additional information regarding copyright ownership.  NetFPGA licenses this
// file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
// "License"); you may not use this file except in compliance with the
// License.  You may obtain a copy of the License at:
//
//   http://www.netfpga-cic.org
//
// Unless required by applicable law or agreed to in writing, Work distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
/////////////////////////////////////////////////////////////////////////////////
// This is an automatically generated header definitions file
/////////////////////////////////////////////////////////////////////////////////

//######################################################
//# Definitions for INPUT_ARBITER
//######################################################
#define NFPLUS_INPUT_ARBITER_BASEADDR 0x00010000
#define NFPLUS_INPUT_ARBITER_HIGHADDR 0x00010FFF
#define NFPLUS_INPUT_ARBITER_SIZEADDR 0x1000

#define NFPLUS_INPUT_ARBITER_0_ID_OFFSET 0x0
#define NFPLUS_INPUT_ARBITER_0_ID_DEFAULT 0x0000DA01
#define NFPLUS_INPUT_ARBITER_0_ID_WIDTH 32
#define NFPLUS_INPUT_ARBITER_0_VERSION_OFFSET 0x4
#define NFPLUS_INPUT_ARBITER_0_VERSION_DEFAULT 0x1
#define NFPLUS_INPUT_ARBITER_0_VERSION_WIDTH 32
#define NFPLUS_INPUT_ARBITER_0_RESET_OFFSET 0x8
#define NFPLUS_INPUT_ARBITER_0_RESET_DEFAULT 0x0
#define NFPLUS_INPUT_ARBITER_0_RESET_WIDTH 16
#define NFPLUS_INPUT_ARBITER_0_FLIP_OFFSET 0xC
#define NFPLUS_INPUT_ARBITER_0_FLIP_DEFAULT 0x0
#define NFPLUS_INPUT_ARBITER_0_FLIP_WIDTH 32
#define NFPLUS_INPUT_ARBITER_0_DEBUG_OFFSET 0x10
#define NFPLUS_INPUT_ARBITER_0_DEBUG_DEFAULT 0x0
#define NFPLUS_INPUT_ARBITER_0_DEBUG_WIDTH 32
#define NFPLUS_INPUT_ARBITER_0_PKTIN_OFFSET 0x14
#define NFPLUS_INPUT_ARBITER_0_PKTIN_DEFAULT 0x0
#define NFPLUS_INPUT_ARBITER_0_PKTIN_WIDTH 32
#define NFPLUS_INPUT_ARBITER_0_PKTOUT_OFFSET 0x18
#define NFPLUS_INPUT_ARBITER_0_PKTOUT_DEFAULT 0x0
#define NFPLUS_INPUT_ARBITER_0_PKTOUT_WIDTH 32

//######################################################
//# Definitions for OUTPUT_QUEUES
//######################################################
#define NFPLUS_OUTPUT_QUEUES_BASEADDR 0x00030000
#define NFPLUS_OUTPUT_QUEUES_HIGHADDR 0x00030FFF
#define NFPLUS_OUTPUT_QUEUES_SIZEADDR 0x1000

#define NFPLUS_OUTPUT_QUEUES_0_ID_OFFSET 0x0
#define NFPLUS_OUTPUT_QUEUES_0_ID_DEFAULT 0x0000DA03
#define NFPLUS_OUTPUT_QUEUES_0_ID_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_VERSION_OFFSET 0x4
#define NFPLUS_OUTPUT_QUEUES_0_VERSION_DEFAULT 0x1
#define NFPLUS_OUTPUT_QUEUES_0_VERSION_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_RESET_OFFSET 0x8
#define NFPLUS_OUTPUT_QUEUES_0_RESET_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_RESET_WIDTH 16
#define NFPLUS_OUTPUT_QUEUES_0_FLIP_OFFSET 0xC
#define NFPLUS_OUTPUT_QUEUES_0_FLIP_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_FLIP_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_DEBUG_OFFSET 0x10
#define NFPLUS_OUTPUT_QUEUES_0_DEBUG_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_DEBUG_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTIN_OFFSET 0x14
#define NFPLUS_OUTPUT_QUEUES_0_PKTIN_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTIN_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTOUT_OFFSET 0x18
#define NFPLUS_OUTPUT_QUEUES_0_PKTOUT_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTOUT_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTSTOREDPORT0_OFFSET 0x1C
#define NFPLUS_OUTPUT_QUEUES_0_PKTSTOREDPORT0_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTSTOREDPORT0_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_BYTESSTOREDPORT0_OFFSET 0x20
#define NFPLUS_OUTPUT_QUEUES_0_BYTESSTOREDPORT0_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_BYTESSTOREDPORT0_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTREMOVEDPORT0_OFFSET 0x24
#define NFPLUS_OUTPUT_QUEUES_0_PKTREMOVEDPORT0_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTREMOVEDPORT0_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_BYTESREMOVEDPORT0_OFFSET 0x28
#define NFPLUS_OUTPUT_QUEUES_0_BYTESREMOVEDPORT0_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_BYTESREMOVEDPORT0_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTDROPPEDPORT0_OFFSET 0x2C
#define NFPLUS_OUTPUT_QUEUES_0_PKTDROPPEDPORT0_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTDROPPEDPORT0_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_BYTESDROPPEDPORT0_OFFSET 0x30
#define NFPLUS_OUTPUT_QUEUES_0_BYTESDROPPEDPORT0_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_BYTESDROPPEDPORT0_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTINQUEUEPORT0_OFFSET 0x34
#define NFPLUS_OUTPUT_QUEUES_0_PKTINQUEUEPORT0_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTINQUEUEPORT0_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTSTOREDPORT1_OFFSET 0x38
#define NFPLUS_OUTPUT_QUEUES_0_PKTSTOREDPORT1_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTSTOREDPORT1_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_BYTESSTOREDPORT1_OFFSET 0x3C
#define NFPLUS_OUTPUT_QUEUES_0_BYTESSTOREDPORT1_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_BYTESSTOREDPORT1_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTREMOVEDPORT1_OFFSET 0x40
#define NFPLUS_OUTPUT_QUEUES_0_PKTREMOVEDPORT1_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTREMOVEDPORT1_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_BYTESREMOVEDPORT1_OFFSET 0x44
#define NFPLUS_OUTPUT_QUEUES_0_BYTESREMOVEDPORT1_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_BYTESREMOVEDPORT1_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTDROPPEDPORT1_OFFSET 0x48
#define NFPLUS_OUTPUT_QUEUES_0_PKTDROPPEDPORT1_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTDROPPEDPORT1_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_BYTESDROPPEDPORT1_OFFSET 0x4C
#define NFPLUS_OUTPUT_QUEUES_0_BYTESDROPPEDPORT1_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_BYTESDROPPEDPORT1_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTINQUEUEPORT1_OFFSET 0x50
#define NFPLUS_OUTPUT_QUEUES_0_PKTINQUEUEPORT1_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTINQUEUEPORT1_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTSTOREDPORT2_OFFSET 0x54
#define NFPLUS_OUTPUT_QUEUES_0_PKTSTOREDPORT2_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTSTOREDPORT2_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_BYTESSTOREDPORT2_OFFSET 0x58
#define NFPLUS_OUTPUT_QUEUES_0_BYTESSTOREDPORT2_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_BYTESSTOREDPORT2_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTREMOVEDPORT2_OFFSET 0x5C
#define NFPLUS_OUTPUT_QUEUES_0_PKTREMOVEDPORT2_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTREMOVEDPORT2_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_BYTESREMOVEDPORT2_OFFSET 0x60
#define NFPLUS_OUTPUT_QUEUES_0_BYTESREMOVEDPORT2_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_BYTESREMOVEDPORT2_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTDROPPEDPORT2_OFFSET 0x64
#define NFPLUS_OUTPUT_QUEUES_0_PKTDROPPEDPORT2_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTDROPPEDPORT2_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_BYTESDROPPEDPORT2_OFFSET 0x68
#define NFPLUS_OUTPUT_QUEUES_0_BYTESDROPPEDPORT2_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_BYTESDROPPEDPORT2_WIDTH 32
#define NFPLUS_OUTPUT_QUEUES_0_PKTINQUEUEPORT2_OFFSET 0x6C
#define NFPLUS_OUTPUT_QUEUES_0_PKTINQUEUEPORT2_DEFAULT 0x0
#define NFPLUS_OUTPUT_QUEUES_0_PKTINQUEUEPORT2_WIDTH 32

//######################################################
//# Definitions for OUTPUT_PORT_LOOKUP
//######################################################
#define NFPLUS_OUTPUT_PORT_LOOKUP_BASEADDR 0x00020000
#define NFPLUS_OUTPUT_PORT_LOOKUP_HIGHADDR 0x00020FFF
#define NFPLUS_OUTPUT_PORT_LOOKUP_SIZEADDR 0x1000

#define NFPLUS_OUTPUT_PORT_LOOKUP_0_ID_OFFSET 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_ID_DEFAULT 0x0000DA01
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_ID_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_VERSION_OFFSET 0x4
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_VERSION_DEFAULT 0x1
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_VERSION_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_RESET_OFFSET 0x8
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_RESET_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_RESET_WIDTH 16
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_FLIP_OFFSET 0xC
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_FLIP_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_FLIP_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_DEBUG_OFFSET 0x10
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_DEBUG_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_DEBUG_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_FROM_CPU_CNTR_OFFSET 0x14
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_FROM_CPU_CNTR_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_FROM_CPU_CNTR_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_OPTIONS_VER_CNTR_OFFSET 0x18
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_OPTIONS_VER_CNTR_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_OPTIONS_VER_CNTR_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_BAD_TTL_CNTR_OFFSET 0x1C
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_BAD_TTL_CNTR_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_BAD_TTL_CNTR_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_DEST_IP_HIT_CNTR_OFFSET 0x20
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_DEST_IP_HIT_CNTR_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_DEST_IP_HIT_CNTR_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_FORWARDED_CNTR_OFFSET 0x24
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_FORWARDED_CNTR_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_FORWARDED_CNTR_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_DROPPED_CHECKSUM_CNTR_OFFSET 0x28
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_DROPPED_CHECKSUM_CNTR_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_DROPPED_CHECKSUM_CNTR_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_NON_IP_CNTR_OFFSET 0x2C
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_NON_IP_CNTR_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_NON_IP_CNTR_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_ARP_MISS_CNTR_OFFSET 0x30
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_ARP_MISS_CNTR_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_ARP_MISS_CNTR_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_LPM_MISS_CNTR_OFFSET 0x34
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_LPM_MISS_CNTR_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_SENT_TO_CPU_LPM_MISS_CNTR_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_DROPPED_WRONG_DST_MAC_CNTR_OFFSET 0x38
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_DROPPED_WRONG_DST_MAC_CNTR_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_PKT_DROPPED_WRONG_DST_MAC_CNTR_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_0_HI_OFFSET 0x3C
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_0_HI_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_0_HI_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_0_LOW_OFFSET 0x40
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_0_LOW_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_0_LOW_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_1_HI_OFFSET 0x44
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_1_HI_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_1_HI_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_1_LOW_OFFSET 0x48
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_1_LOW_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_1_LOW_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_2_HI_OFFSET 0x4C
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_2_HI_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_2_HI_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_2_LOW_OFFSET 0x50
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_2_LOW_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_2_LOW_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_3_HI_OFFSET 0x54
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_3_HI_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_3_HI_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_3_LOW_OFFSET 0x58
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_3_LOW_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MAC_3_LOW_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTADDRESS_OFFSET 0x5C
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTADDRESS_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTADDRESS_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTWRDATA_A_HI_OFFSET 0x60
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTWRDATA_A_HI_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTWRDATA_A_HI_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTWRDATA_A_LOW_OFFSET 0x64
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTWRDATA_A_LOW_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTWRDATA_A_LOW_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTWRDATA_B_HI_OFFSET 0x68
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTWRDATA_B_HI_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTWRDATA_B_HI_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTWRDATA_B_LOW_OFFSET 0x6C
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTWRDATA_B_LOW_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTWRDATA_B_LOW_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTREPLY_A_HI_OFFSET 0x70
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTREPLY_A_HI_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTREPLY_A_HI_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTREPLY_A_LOW_OFFSET 0x74
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTREPLY_A_LOW_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTREPLY_A_LOW_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTREPLY_B_HI_OFFSET 0x78
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTREPLY_B_HI_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTREPLY_B_HI_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTREPLY_B_LOW_OFFSET 0x7C
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTREPLY_B_LOW_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTREPLY_B_LOW_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTCOMMAND_OFFSET 0x80
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTCOMMAND_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTCOMMAND_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTCONFIG_OFFSET 0x84
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTCONFIG_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_INDIRECTCONFIG_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MEM_IP_LPM_TCAM_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MEM_IP_LPM_TCAM_DEPTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MEM_IP_LPM_TCAM_ADDRESS 0x00000000
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MEM_IP_ARP_CAM_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MEM_IP_ARP_CAM_DEPTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MEM_IP_ARP_CAM_ADDRESS 0x10000000
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MEM_DEST_IP_CAM_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MEM_DEST_IP_CAM_DEPTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_0_MEM_DEST_IP_CAM_ADDRESS 0x20000000

