// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="krnl_mm2s_krnl_mm2s,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.433090,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=30,HLS_SYN_DSP=0,HLS_SYN_FF=4039,HLS_SYN_LUT=4059,HLS_VERSION=2021_2}" *)

module krnl_mm2s (
        ap_local_block,
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        k2n_TDATA,
        k2n_TVALID,
        k2n_TREADY,
        k2n_TKEEP,
        k2n_TSTRB,
        k2n_TUSER,
        k2n_TLAST,
        k2n_TID,
        k2n_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 512;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (512 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

output   ap_local_block;
input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
output  [511:0] k2n_TDATA;
output   k2n_TVALID;
input   k2n_TREADY;
output  [63:0] k2n_TKEEP;
output  [63:0] k2n_TSTRB;
output  [0:0] k2n_TUSER;
output  [0:0] k2n_TLAST;
output  [0:0] k2n_TID;
output  [15:0] k2n_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

wire   [0:0] ap_local_deadlock;
(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] in_r;
wire   [31:0] size;
wire   [31:0] dest;
reg   [63:0] in_r_read_reg_166;
wire   [25:0] div_cast_fu_132_p4;
reg   [25:0] div_cast_reg_171;
wire   [26:0] sub_fu_146_p2;
reg   [26:0] sub_reg_177;
wire   [15:0] empty_fu_152_p1;
reg   [15:0] empty_reg_182;
reg   [57:0] trunc_ln72_1_reg_187;
wire    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_start;
wire    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_done;
wire    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_idle;
wire    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_ready;
wire    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWVALID;
wire   [63:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWADDR;
wire   [0:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWID;
wire   [31:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWLEN;
wire   [2:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWSIZE;
wire   [1:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWBURST;
wire   [1:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWLOCK;
wire   [3:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWCACHE;
wire   [2:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWPROT;
wire   [3:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWQOS;
wire   [3:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWREGION;
wire   [0:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWUSER;
wire    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_WVALID;
wire   [511:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_WDATA;
wire   [63:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_WSTRB;
wire    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_WLAST;
wire   [0:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_WID;
wire   [0:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_WUSER;
wire    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARVALID;
wire   [63:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARADDR;
wire   [0:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARID;
wire   [31:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARLEN;
wire   [2:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARSIZE;
wire   [1:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARBURST;
wire   [1:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARLOCK;
wire   [3:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARCACHE;
wire   [2:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARPROT;
wire   [3:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARQOS;
wire   [3:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARREGION;
wire   [0:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARUSER;
wire    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_RREADY;
wire    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_BREADY;
wire   [511:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TDATA;
wire    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TVALID;
wire    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TREADY;
wire   [63:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TKEEP;
wire   [63:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TSTRB;
wire   [0:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TUSER;
wire   [0:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TLAST;
wire   [0:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TID;
wire   [15:0] grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TDEST;
wire    gmem_AWREADY;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [511:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [8:0] gmem_RFIFONUM;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg    grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    ap_block_state1;
wire   [26:0] div_cast_cast_fu_142_p1;
wire    ap_CS_fsm_state4;
wire    regslice_both_k2n_V_data_V_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    k2n_TVALID_int_regslice;
wire    k2n_TREADY_int_regslice;
wire    regslice_both_k2n_V_data_V_U_vld_out;
wire    regslice_both_k2n_V_keep_V_U_apdone_blk;
wire    regslice_both_k2n_V_keep_V_U_ack_in_dummy;
wire    regslice_both_k2n_V_keep_V_U_vld_out;
wire    regslice_both_k2n_V_strb_V_U_apdone_blk;
wire    regslice_both_k2n_V_strb_V_U_ack_in_dummy;
wire    regslice_both_k2n_V_strb_V_U_vld_out;
wire    regslice_both_k2n_V_user_V_U_apdone_blk;
wire    regslice_both_k2n_V_user_V_U_ack_in_dummy;
wire    regslice_both_k2n_V_user_V_U_vld_out;
wire    regslice_both_k2n_V_last_V_U_apdone_blk;
wire    regslice_both_k2n_V_last_V_U_ack_in_dummy;
wire    regslice_both_k2n_V_last_V_U_vld_out;
wire    regslice_both_k2n_V_id_V_U_apdone_blk;
wire    regslice_both_k2n_V_id_V_U_ack_in_dummy;
wire    regslice_both_k2n_V_id_V_U_vld_out;
wire    regslice_both_k2n_V_dest_V_U_apdone_blk;
wire    regslice_both_k2n_V_dest_V_U_ack_in_dummy;
wire    regslice_both_k2n_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_start_reg = 1'b0;
end

krnl_mm2s_krnl_mm2s_Pipeline_VITIS_LOOP_69_1 grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_start),
    .ap_done(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_done),
    .ap_idle(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_idle),
    .ap_ready(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_ready),
    .m_axi_gmem_AWVALID(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(gmem_RLAST),
    .m_axi_gmem_RID(gmem_RID),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(gmem_RUSER),
    .m_axi_gmem_RRESP(gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln72_1(trunc_ln72_1_reg_187),
    .div_cast(div_cast_reg_171),
    .v_dest_V(empty_reg_182),
    .k2n_TDATA(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TDATA),
    .k2n_TVALID(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TVALID),
    .k2n_TREADY(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TREADY),
    .k2n_TKEEP(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TKEEP),
    .k2n_TSTRB(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TSTRB),
    .k2n_TUSER(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TUSER),
    .k2n_TLAST(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TLAST),
    .k2n_TID(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TID),
    .k2n_TDEST(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TDEST),
    .in_r(in_r_read_reg_166),
    .empty(div_cast_reg_171),
    .sub(sub_reg_177)
);

krnl_mm2s_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in_r(in_r),
    .size(size),
    .dest(dest),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle),
    .ap_local_deadlock(ap_local_deadlock)
);

krnl_mm2s_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_DW( 512 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARADDR),
    .I_ARID(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARID),
    .I_ARLEN(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARLEN),
    .I_ARSIZE(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARSIZE),
    .I_ARLOCK(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARLOCK),
    .I_ARCACHE(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARCACHE),
    .I_ARQOS(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARQOS),
    .I_ARPROT(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARPROT),
    .I_ARUSER(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARUSER),
    .I_ARBURST(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARBURST),
    .I_ARREGION(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARREGION),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(512'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(64'd0),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

krnl_mm2s_regslice_both #(
    .DataWidth( 512 ))
regslice_both_k2n_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TDATA),
    .vld_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TVALID),
    .ack_in(k2n_TREADY_int_regslice),
    .data_out(k2n_TDATA),
    .vld_out(regslice_both_k2n_V_data_V_U_vld_out),
    .ack_out(k2n_TREADY),
    .apdone_blk(regslice_both_k2n_V_data_V_U_apdone_blk)
);

krnl_mm2s_regslice_both #(
    .DataWidth( 64 ))
regslice_both_k2n_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TKEEP),
    .vld_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TVALID),
    .ack_in(regslice_both_k2n_V_keep_V_U_ack_in_dummy),
    .data_out(k2n_TKEEP),
    .vld_out(regslice_both_k2n_V_keep_V_U_vld_out),
    .ack_out(k2n_TREADY),
    .apdone_blk(regslice_both_k2n_V_keep_V_U_apdone_blk)
);

krnl_mm2s_regslice_both #(
    .DataWidth( 64 ))
regslice_both_k2n_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TSTRB),
    .vld_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TVALID),
    .ack_in(regslice_both_k2n_V_strb_V_U_ack_in_dummy),
    .data_out(k2n_TSTRB),
    .vld_out(regslice_both_k2n_V_strb_V_U_vld_out),
    .ack_out(k2n_TREADY),
    .apdone_blk(regslice_both_k2n_V_strb_V_U_apdone_blk)
);

krnl_mm2s_regslice_both #(
    .DataWidth( 1 ))
regslice_both_k2n_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TUSER),
    .vld_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TVALID),
    .ack_in(regslice_both_k2n_V_user_V_U_ack_in_dummy),
    .data_out(k2n_TUSER),
    .vld_out(regslice_both_k2n_V_user_V_U_vld_out),
    .ack_out(k2n_TREADY),
    .apdone_blk(regslice_both_k2n_V_user_V_U_apdone_blk)
);

krnl_mm2s_regslice_both #(
    .DataWidth( 1 ))
regslice_both_k2n_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TLAST),
    .vld_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TVALID),
    .ack_in(regslice_both_k2n_V_last_V_U_ack_in_dummy),
    .data_out(k2n_TLAST),
    .vld_out(regslice_both_k2n_V_last_V_U_vld_out),
    .ack_out(k2n_TREADY),
    .apdone_blk(regslice_both_k2n_V_last_V_U_apdone_blk)
);

krnl_mm2s_regslice_both #(
    .DataWidth( 1 ))
regslice_both_k2n_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TID),
    .vld_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TVALID),
    .ack_in(regslice_both_k2n_V_id_V_U_ack_in_dummy),
    .data_out(k2n_TID),
    .vld_out(regslice_both_k2n_V_id_V_U_vld_out),
    .ack_out(k2n_TREADY),
    .apdone_blk(regslice_both_k2n_V_id_V_U_apdone_blk)
);

krnl_mm2s_regslice_both #(
    .DataWidth( 16 ))
regslice_both_k2n_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TDEST),
    .vld_in(grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TVALID),
    .ack_in(regslice_both_k2n_V_dest_V_U_ack_in_dummy),
    .data_out(k2n_TDEST),
    .vld_out(regslice_both_k2n_V_dest_V_U_vld_out),
    .ack_out(k2n_TREADY),
    .apdone_blk(regslice_both_k2n_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_k2n_V_data_V_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_ready == 1'b1)) begin
            grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        div_cast_reg_171 <= {{size[31:6]}};
        empty_reg_182 <= empty_fu_152_p1;
        in_r_read_reg_166 <= in_r;
        sub_reg_177 <= sub_fu_146_p2;
        trunc_ln72_1_reg_187 <= {{in_r[63:6]}};
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_k2n_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_k2n_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_k2n_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_ARVALID = grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_RREADY = grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_k2n_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'd0;

assign div_cast_cast_fu_142_p1 = div_cast_fu_132_p4;

assign div_cast_fu_132_p4 = {{size[31:6]}};

assign empty_fu_152_p1 = dest[15:0];

assign grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_start = grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_ap_start_reg;

assign grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TREADY = (k2n_TREADY_int_regslice & ap_CS_fsm_state3);

assign k2n_TVALID = regslice_both_k2n_V_data_V_U_vld_out;

assign k2n_TVALID_int_regslice = grp_krnl_mm2s_Pipeline_VITIS_LOOP_69_1_fu_106_k2n_TVALID;

assign sub_fu_146_p2 = ($signed(div_cast_cast_fu_142_p1) + $signed(27'd134217727));

endmodule //krnl_mm2s
